logger_level: Logger::INFO

#### Browser driver configs ####

webdriver:
  browser: chrome
  headless: false
  chrome_binary_path: '/Applications/Google Chrome for Testing.app'

timeouts:
  click_wait: 0.5
  short: 8
  medium: 30
  long: 120
  canvas_poller: 60

#### Test user accounts ####

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  super_admin_canvas_id: secret
  oski_uid: secret

#### Test environment configs ####

cal_net:
  base_url: https://auth-test.berkeley.edu

canvas:
  base_url: https://ucberkeley.test.instructure.com
  admin_sub_account: secret
  uc_berkeley_sub_account: secret
  official_courses_sub_account: secret
  qa_sub_account: secret
  enrollment_retries: 25

nessie:
  pg_db_host: secret
  pg_db_port: secret
  pg_db_name: secret
  pg_db_user: secret
  pg_db_password: secret

ripley:
  base_url: https://ripley-qa.ets.berkeley.edu
  base_url_prod: https://ripley.ets.berkeley.edu
  dev_auth_password: secret
  admin_uid: secret
  term_name: 'Spring 2023'
  term_code: '2023-B'
  term_sis_id: '2232'
  recent_refresh_days_past: 180
  course_template_dept: 'LAW'
  course_prefixes: ['ECON C', 'CHEM 1A', 'LAW']
  e_grades_site_ids: ['123', '456', '789']
  e_grades_student_count: 10
  newt_site_ids: ['987', '654', '321']
  db_host: secret
  db_port: secret
  db_name: secret
  db_user: secret
  db_password: secret
  newt_min_grade_count: 0
  newt_small_cell_supp: 10
  test_users:
    - uid: 123456
      canvas_id: 654321
      email: 'catherine-a@email.com'
      full_name: 'Catherine of Aragon'
      role: 'Teacher'
    - uid: 234567
      canvas_id: 765432
      email: 'anne-b@email.com'
      full_name: 'Anne Boleyn'
      role: 'Lead TA'
    - uid: 345678
      canvas_id: 876543
      email: 'jane-s@email.com'
      full_name: 'Jane Seymour'
      role: 'Student'
    - uid: 456789
      canvas_id: 987654
      email: 'anne-c@email.com'
      full_name: 'Anne of Cleves'
      role: 'Reader'
    - uid: 567890
      canvas_id: 098765
      email: 'catherine-h@email.com'
      full_name: 'Catherine Howard'
      role: 'Owner'
    - uid: 678901
      canvas_id: 109876
      email: 'catherine-p@email.com'
      full_name: 'Catherine Parr'
      role: 'Member'
